# Writing Good Code

## Don't Repeat Yourself

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv("../data/sdg_literacy_rate.csv")
df = df.drop(["Series Name", "Series Code", "Country Code"], axis=1)
df = df.set_index("Country Name").transpose()

In [19]:
df.head()

Country Name,World,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Arab World,Argentina,...,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe,NaN,NaN,NaN,Data from database: Sustainable Development Goals (SDGs),Last Updated: 07/22/2022
1990 [YR1990],83.1576919555664,..,..,..,..,..,..,..,72.4959869384766,..,...,..,..,..,66.3811569213867,..,NaN,NaN,NaN,NaN,NaN
1991 [YR1991],83.3608779907227,..,..,..,..,..,..,..,73.9646987915039,98.3046417236328,...,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN
1992 [YR1992],83.6726989746094,..,..,..,..,..,..,..,74.9201431274414,..,...,..,..,..,..,95.4113616943359,NaN,NaN,NaN,NaN,NaN
1993 [YR1993],83.9159317016602,..,..,..,..,..,..,..,74.6631469726563,..,...,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN
1994 [YR1994],84.1862030029297,..,..,..,..,..,..,..,75.5125732421875,..,...,..,..,60.2221412658691,..,..,NaN,NaN,NaN,NaN,NaN

In [20]:
df2 = pd.read_csv("../data/sdg_electricity_data.csv")
df2 = df2.drop(["Series Name", "Series Code", "Country Code"], axis=1)
df2 = df2.set_index("Country Name").transpose()

In [21]:
df3 = pd.read_csv("../data/sdg_urban_population.csv")
df3 = df3.drop(["Series Name", "Series Code", "Country Code"], axis=1)
df3 = df3.set_index("Country Name").transpose()

You can avoid the repetition by turning this into a function:

In [22]:
def process_sdg_data(csv_file, columns_to_drop):
    df = pd.read_csv(csv_file)
    df = df.drop(columns_to_drop, axis=1)
    df = df.set_index("Country Name").transpose()
    return df

In [23]:
df = process_sdg_data("../data/sdg_literacy_rate.csv", ["Series Name", "Series Code", "Country Code"])

In [24]:
df.head()

Country Name,World,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Antigua and Barbuda,Arab World,Argentina,...,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe,NaN,NaN,NaN,Data from database: Sustainable Development Goals (SDGs),Last Updated: 07/22/2022
1990 [YR1990],83.1576919555664,..,..,..,..,..,..,..,72.4959869384766,..,...,..,..,..,66.3811569213867,..,NaN,NaN,NaN,NaN,NaN
1991 [YR1991],83.3608779907227,..,..,..,..,..,..,..,73.9646987915039,98.3046417236328,...,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN
1992 [YR1992],83.6726989746094,..,..,..,..,..,..,..,74.9201431274414,..,...,..,..,..,..,95.4113616943359,NaN,NaN,NaN,NaN,NaN
1993 [YR1993],83.9159317016602,..,..,..,..,..,..,..,74.6631469726563,..,...,..,..,..,..,..,NaN,NaN,NaN,NaN,NaN
1994 [YR1994],84.1862030029297,..,..,..,..,..,..,..,75.5125732421875,..,...,..,..,60.2221412658691,..,..,NaN,NaN,NaN,NaN,NaN

In [25]:
df2 = process_sdg_data("../data/sdg_electricity_data.csv",["Series Name", "Series Code", "Country Code"])
df2.head()

Country Name,Arab World,Caribbean small states,Central Europe and the Baltics,Early-demographic dividend,East Asia & Pacific,East Asia & Pacific (excluding high income),East Asia & Pacific (IDA & IBRD),Euro area,Europe & Central Asia,Europe & Central Asia (excluding high income),...,Virgin Islands (U.S.),West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe,NaN,NaN,NaN,NaN,NaN
1990 [YR1990],..,..,100,..,..,..,..,100,100,100,...,100,..,..,13.9,..,NaN,NaN,NaN,NaN,NaN
2000 [YR2000],80.7361412102573,86.8292942974403,100,66.7030724363987,92.2236372239929,91.3174717523684,91.3175185415022,100,99.9493964240866,99.8816190704524,...,100,99.6999969482422,49.187255859375,16.7000007629395,33.6548881530762,NaN,NaN,NaN,NaN,NaN
2011 [YR2011],87.3326612400273,93.3906480037973,100,75.1718689357295,96.1416216132401,95.7161531660522,96.5262079766799,100,99.9678361247815,99.9244805349554,...,100,99.6999969482422,61.8645057678223,28.1590099334717,36.9000015258789,NaN,NaN,NaN,NaN,NaN
2012 [YR2012],87.0395883900211,94.4029957151005,100,81.1046083548977,96.3971680759818,96.001969136835,96.7844602546104,100,99.9810754122,99.9557778282364,...,100,99.8000030517578,52.4099998474121,29.0127258300781,44,NaN,NaN,NaN,NaN,NaN
2013 [YR2013],88.992619805618,94.8869223835886,100,82.2652548788111,96.6026789439967,96.2321106504147,96.9863737965289,100,99.9772262352054,99.9468866178254,...,100,99.9000015258789,75.5999984741211,29.8862724304199,40.4983749389648,NaN,NaN,NaN,NaN,NaN